### ISSUE TITLE
Styled Markup Feedback!

### ISSUE THREAD

**Issue by rijkvanzanten** [gallr091/manuscript#2]
- [ ] Git(Hub) keeps track of all the changes to every file, so there's no need to have manual copies for "original" "version2" "final-for-real-this-time". Stick to just one `index.html` and let Git handle the changes tracking. You can always go back to a previous version.
  ![CleanShot 2024-09-30 at 09 19 57@2x](https://github.com/user-attachments/assets/bcc0cef7-acd9-44dd-bcbf-26a6cd6270c0)
- [ ] .. that also means I'm not entirely sure which file you intend me to look at 😬 (I'm going to assume `index.html` and the files it imports
- [ ] [When importing fonts through CSS](https://github.com/gallr091/manuscript/blob/21cfcf661f4b0e295002d26c21169117463950c2/index.html#L7-L10), put them in the CSS file instead of head. (I'd recommend importing them through the `link` tags though, as it's generally better for performance)
- [ ] `div.slide.title` feels like a prime candidate to become a [`header`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header)
- [ ] [A `br` tag shouldn't be used for stylistic purposes.](https://github.com/gallr091/manuscript/blob/21cfcf661f4b0e295002d26c21169117463950c2/index.html#L18C3-L19). In this case, you're trying to force those inline `span` elements to behave like a block. A `div` is a block by default, so by replacing the `span`s with `div`s there you get the wrapping for free
- [ ] [I feel like this should be a `time { font-style: italic }` rather than a `<i>`](https://github.com/gallr091/manuscript/blob/21cfcf661f4b0e295002d26c21169117463950c2/index.html#L44)
- [ ] [Your indentation is starting to get a bit messy](https://github.com/gallr091/manuscript/blob/21cfcf661f4b0e295002d26c21169117463950c2/index.html#L202-L203); sometimes things aren't indented when they should, indented when they shouldn't, tabs spaces mixed etc.
- [ ] [ಠ_ಠ](https://github.com/gallr091/manuscript/blob/21cfcf661f4b0e295002d26c21169117463950c2/index.html#L250)
- [ ] [You're setting overflow-y twice](https://github.com/gallr091/manuscript/blob/21cfcf661f4b0e295002d26c21169117463950c2/styles.css#L7-L12)
- [ ] We'll get to this in more detail when we'll get to responsive design, but generally speaking making overflows hidden is a bit of a foot-gun. When the browser window changes, content can and will flow outside of the box unintentionally, and if you've designed the work in a way where it's forced cut off, you make it unaccessible to your end user. For this project it doesn't matter yet, but something to be aware of for future projects 🙂 
- [ ] [Fast forward to week 8](https://github.com/gallr091/manuscript/blob/21cfcf661f4b0e295002d26c21169117463950c2/styles.css#L25-L26) 😄⏩ 
- [ ] [Noticing a lot of repeated code](https://github.com/gallr091/manuscript/blob/21cfcf661f4b0e295002d26c21169117463950c2/styles.css#L594-L672). Once you find yourself repeating the same css over and over again, you're probably better off using a comma separated selector. For example:
  ```css
  /* ============================================== */
  /* Before */
  .flat p:nth-child(5){
    position:relative;
    padding: 5px;
    width: 500px;
    left: 650px;
    top: -613px;
  }

  .flat p:nth-child(6){
    position:relative;
    padding: 5px;
    width: 500px;
    left: 650px;
    top: -613px;
  }

  .flat p:nth-child(7){
    position:relative;
    padding: 5px;
    width: 500px;
    left: 650px;
    top: -613px;
  }

  /* ============================================== */
  /* After */
  .flat p:nth-child(5),
  .flat p:nth-child(6),
  .flat p:nth-child(7) {
    position:relative;
    padding: 5px;
    width: 500px;
    left: 650px;
    top: -613px;
  }
  ```
- [ ] Seeing you grasped for some JS, I feel like it's worth pointing out why this bit doesn't _quite_ work (unfortunately). The `wheel` event runs _synchronously_, meaning that the browser has to wait until the code is done running before the next cycle can fire. This in turn means that on lower powered devices (eg everything that isn't your thousands $ MacBook) it will have trouble keeping up and become choppy. That'd obviously be a very bad user experience 😬 
- [ ] Try positioning the paragraphs relative to the individual slides instead of the viewport. By setting `position: relative` on the parent slide section, the `left/top` of the children become relative to the slide rather than body. That way you don't have to end up with a bunch of magic numbers like left: 3050px which will only work on your machine

In general, when working on something so ambitious, make sure you don't lose the basics out of sight. It's easy to get distracted by the shiny things and have the rest suffer from your attention being diverted 🙂
